name: Sec CI
permissions:
  contents: read
  pull-requests: read
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Go Env
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true
        id: go

      - name: Test
        run: go test -v ./...
